[tools]
rust = "latest"
"cargo:cargo-zigbuild" = "latest"
zig = "0.14.0"

[tasks.setup]
run = [
    "rustup target add x86_64-unknown-linux-gnu",
]

[tasks.test]
run = [
    "cargo zigbuild -p vscfreedev-remote --target x86_64-unknown-linux-gnu"
]