[package]
name = "vscfreedev-client"
version = "0.0.1"
edition = "2024"

[dependencies]
vscfreedev-core = { workspace = true }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "sync", "time", "fs", "process"] }
anyhow = "1"
thiserror = "2"
russh = "0.45"
russh-keys = "0.45"
async-trait = "0.1"
futures = "0.3"

[dev-dependencies]
tempfile = "3.8"
rand = "0.9"
bytes = "1.0"
