[package]
name = "vscfreedev-core"
version = { workspace = true }
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "sync", "time"] }
anyhow = "1"
thiserror = "2"
bytes = "1"
base64 = "0.22"
