[package]
name = "vscfreedev-core"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
description = "Core functionality for vscfreedev"

[dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "net", "io-util", "sync", "time"] }
anyhow = { workspace = true }
thiserror = { workspace = true }
bytes = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
